[tool.poetry]
name = "mlrd"
version = "0.1.3"
description = "Mcgrill Lecture Recording Download (mlrd) tool"
authors = ["Brendan <bshizzle1234@gmail.com>"]
license = "MIT"
repository = "https://github.com/brendan-kellam/mlrd"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mlrd = 'mlrd.__main__:main'