[tool.poetry]
name = "mimosa-monomer"
version = "0.2.0"
description = "CLI for Stilt 2 database."
authors = ["Daniel Hampton <dhampton084@gmail.com>"]
readme = "README.md"
classifiers = [
 "Environment :: Console",
 "Operating System :: OS Independent",
 "Topic :: Database",
 "Topic :: Utilities",
]
packages = [
  { include = "mimosa", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.6"
attrs = "^19.3.0"
firebase-admin = "^3.2.1"
halo = "^0.0.28"
typer = "^0.3.2"
click = "^7.0"
cutie = "^0.2.2"
cerberus = "^1.3.2"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
pytest-mock = "^2.0.0"
pytest-cov = "^2.8.1"
tox = "^3.20.1"
black = "^20.8b1"
tox-pyenv = "^1.1.0"

[tool.poetry.scripts]
mimosa = "mimosa.main:main"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
